![Introduction to Numpy](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH9SVEHRKBwkUd4lBul8wKdhbSCa5HEZ84wFWYu2ubMw&s)

### Basics Of Numpy (Numerical Python)

In [1]:
import numpy as np
array = np.array([1,2,3,4,5]) # array is just a simple python list
array

array([1, 2, 3, 4, 5])

In [3]:
array[0], array[1]

(1, 2)

- 2D array

In [4]:
"""
[[],[],[]]
"""
two_d_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(f"Dimensions of Simple array: {array.ndim}")
print(f"Dimensions of 2D array: {two_d_array.ndim}")

Dimensions of Simple array: 1
Dimensions of 2D array: 2


In [6]:
two_d_array.dtype

dtype('int32')

`array.itemsize` will return the size of each array element in bytes.

In [7]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.float64)
array.itemsize

8

In [8]:
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

- Size property

In [9]:
array.size

9

- Shape property

In [10]:
array.shape

(3, 3)

In [11]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=complex)
array

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

- Generating array of zeros

In [12]:
np.zeros((3,4)) # np.zeros((rows, cols))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- Generating array of ones

In [13]:
np.ones((5,6)) # np.ones((rows, cols))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

- Arange() function

In [14]:
np.arange(1,10) # Similar to python range(1,5) function

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
"""
1,2,3,4,5,6,7,8,9

"""
np.arange(1,10,2) 
np.arange(1,10,3) 

array([1, 4, 7])

- linspace() function

`np.linspace` will generate numbers(10) from start (1) to end (5) which are linearly spaced

In [16]:
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
array = np.array([
    [1,2,3], 
    [4,5,6]
])
array.shape

(2, 3)

- reshape() function

In [36]:
array.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
array.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [39]:
array_ravel = np.array([[1,2,3],[4,5,6]])
array.ravel()

array([1, 2, 3, 4, 5, 6])

In [25]:
array

array([[1, 2, 3],
       [4, 5, 6]])

- Some Basic Operations with Arrays

In [26]:
print(f"Min: {array.min()}")
print(f"Max: {array.max()}")
print(f"Sum: {array.sum()}")
print(f"Sum along columns: {array.sum(axis=0)}")
print(f"Sum along rows: {array.sum(axis=1)}")

Min: 1
Max: 6
Sum: 21
Sum along columns: [5 7 9]
Sum along rows: [ 6 15]


In [27]:
np.sqrt(array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
array_one = np.array([1,2,3])
array_two = np.array([4,5,6])
array_one + array_two

array([5, 7, 9])

In [29]:
array_one * array_two

array([ 4, 10, 18])

In [30]:
array_one - array_two

array([-3, -3, -3])

In [31]:
array_one / array_two

array([0.25, 0.4 , 0.5 ])

In [40]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
array_one.dot(array_two) # 4*1 + 2*5 + 6*3 = 32

32